version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/myapp
    overwrite: yes

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 30
      runas: root

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 30
      runas: root

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 30
      runas: root
